version: '3'

services:
  # frontend:
  #   build: ./front-end
  #   container_name: front-end_ecommerce
  #   working_dir: /srv/frontend
  #   env_file: .env
  #   ports:
  #     - '${PORT_FRONT}:${PORT_FRONT}'
  #   restart: always
  #   networks:
  #     - project-kleber

  backend:
    env_file:
      - .env
    build: ./back-end
    container_name: backend_marketplace
    ports:
      - '${PORT_BACK}:${PORT_BACK}'
    restart: always
    networks:
      - project-kleber
    depends_on:
      - db

  db:
    env_file:
      - .env
    container_name: db_marketplace
    image: mysql:5.7
    ports:
      - '${PORT_DB}:${PORT_DB}'
    networks:
      - project-kleber
    restart: always

networks:
  project-kleber:
    name: project-kleber